#version: "3.9"

services:
  fastapi:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - mysql-db
    environment:
      - DATABASE_URL=${DATABASE_URL}

    volumes:
      - .:/myforeignjob
    networks:
      - myforeignjob_app-network

  mysql-db:
    image: mysql:5.7
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root#123
      MYSQL_DATABASE: myforeignjob_dbs
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - myforeignjob_app-network

volumes:
  mysql_data:

networks:
  myforeignjob_app-network: