version: '3.9'

services:
  db:
    image: mysql:8.0
    container_name: myforeignjob_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myforeignjob_dbs
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: myforeignjob_backend
    restart: always
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
    environment:
      CONFIG_PATH: myforeignjob/config.ini

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: myforeignjob_frontend
    restart: always
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  mysql_data:

networks:
  app-network:
